### ISSUE TITLE
Feature flags not updating after temporary connection loss

### ISSUE THREAD

**Issue by AndriyKhavro** [launchdarkly/dotnet-client#88]
In a steaming mode, when connection fails and is not recovered after some time, LdClient doesn't seem to reconnect again. This caused us to switch to polling mode instead of streaming.

I tested it on my machine by turning off internet connection.

Here is a simple repo to reproduce the issue: https://github.com/AndriyKhavro/ld-client-connection-issue. Program outputs stale feature flags after connection is lost, even after it is recovered.

Here are the logs a few minutes after turning off the connection:

```
8/28/2018 8:07:34 PM [ERROR] LaunchDarkly.Common.StreamManager - Encountered EventSource error: A timeout occurred while reading the request from the remote EventSource API
=======================================================(inner most exception)===
 (1) System.Net.Http.HttpRequestException
================================================================================

Message:
"A timeout occurred while reading the request from the remote EventSource API"

Stack Trace:
   at LaunchDarkly.EventSource.EventSourceService.ProcessResponseFromReaderAsync(Action`1 processResponse, IStreamReader reader, CancellationToken cancellationToken)
   at LaunchDarkly.EventSource.EventSourceService.ConnectToEventSourceApi(Action`1 processResponse, CancellationToken cancellationToken)
   at LaunchDarkly.EventSource.EventSourceService.GetDataAsync(Action`1 processResponse, CancellationToken cancellationToken)
   at LaunchDarkly.EventSource.EventSource.ConnectToEventSourceAsync(CancellationToken cancellationToken)
================================================================================

8/28/2018 8:07:34 PM [ERROR] LaunchDarkly.EventSource.EventSource - Encountered an error connecting to EventSource: A timeout occurred while reading the request from the remote EventSource API
=======================================================(inner most exception)===
 (1) System.Net.Http.HttpRequestException
================================================================================

Message:
"A timeout occurred while reading the request from the remote EventSource API"

Stack Trace:
   at LaunchDarkly.EventSource.EventSourceService.ProcessResponseFromReaderAsync(Action`1 processResponse, IStreamReader reader, CancellationToken cancellationToken)
   at LaunchDarkly.EventSource.EventSourceService.ConnectToEventSourceApi(Action`1 processResponse, CancellationToken cancellationToken)
   at LaunchDarkly.EventSource.EventSourceService.GetDataAsync(Action`1 processResponse, CancellationToken cancellationToken)
   at LaunchDarkly.EventSource.EventSource.ConnectToEventSourceAsync(CancellationToken cancellationToken)
   at LaunchDarkly.EventSource.EventSource.StartAsync()
================================================================================

8/28/2018 8:07:34 PM [DEBUG] LaunchDarkly.EventSource.EventSource - 
=======================================================(inner most exception)===
 (1) System.Net.Http.HttpRequestException
================================================================================

Message:
"A timeout occurred while reading the request from the remote EventSource API"

Stack Trace:
   at LaunchDarkly.EventSource.EventSourceService.ProcessResponseFromReaderAsync(Action`1 processResponse, IStreamReader reader, CancellationToken cancellationToken)
   at LaunchDarkly.EventSource.EventSourceService.ConnectToEventSourceApi(Action`1 processResponse, CancellationToken cancellationToken)
   at LaunchDarkly.EventSource.EventSourceService.GetDataAsync(Action`1 processResponse, CancellationToken cancellationToken)
   at LaunchDarkly.EventSource.EventSource.ConnectToEventSourceAsync(CancellationToken cancellationToken)
   at LaunchDarkly.EventSource.EventSource.StartAsync()
================================================================================

8/28/2018 8:07:34 PM [INFO]  LaunchDarkly.EventSource.EventSource - Waiting 1316 milliseconds before reconnecting...
8/28/2018 8:07:35 PM [DEBUG] LaunchDarkly.Common.StreamManager - Eventsource Closed
8/28/2018 8:07:35 PM [ERROR] LaunchDarkly.Common.StreamManager - Encountered EventSource error: Http Status Code '502' indicates an unsuccessful response returned from the remote EventSource API.
=======================================================(inner most exception)===
 (1) LaunchDarkly.EventSource.EventSourceServiceUnsuccessfulResponseException
================================================================================

Message:
"Http Status Code '502' indicates an unsuccessful response returned from the remote EventSource API."

Properties:
  Int32.StatusCode = "502"

Stack Trace:
   at LaunchDarkly.EventSource.EventSourceService.HandleUnsuccessfulStatusCodes(HttpResponseMessage response)
   at LaunchDarkly.EventSource.EventSourceService.HandleInvalidResponses(HttpResponseMessage response)
   at LaunchDarkly.EventSource.EventSourceService.ConnectToEventSourceApi(Action`1 processResponse, CancellationToken cancellationToken)
   at LaunchDarkly.EventSource.EventSourceService.GetDataAsync(Action`1 processResponse, CancellationToken cancellationToken)
   at LaunchDarkly.EventSource.EventSource.ConnectToEventSourceAsync(CancellationToken cancellationToken)
================================================================================

8/28/2018 8:07:35 PM [ERROR] LaunchDarkly.Common.StreamManager - HTTP error 502 for streaming connection - will retry
```

No logs after I turned the connection back on.

**Comment by eli-darkly** [comment]
Sorry for this problem - we're looking into it. I suspect that the triggering factor may not be the length of time that the connection is down, but the nature of the error received after the reconnect attempt - i.e. after an I/O error it does retry, but after an HTTP 502 it says it will retry but doesn't. But we'll know more once we reproduce it.

**Comment by eli-darkly** [comment]
We should have a fix shortly. As I thought, the reconnect logic was working correctly in the case where network connectivity was temporarily lost - which is the most common condition - but it did not retry the connection if it managed to reach the server and then received an HTTP error status.

**Comment by eli-darkly** [comment]
Sorry for the delay - we have the fix and are trying to release it, but some kind of outage at NuGet is getting in the way.

**Comment by eli-darkly** [comment]
OK, patch release 5.3.1 is out now with this fix. Testing the fix on your own could be difficult, since just turning the network connectivity off and on would not necessarily reproduce the problem - the failure to retry would occur if the remote server returned an HTTP error status, which is not a common type of outage. But we've tested it internally with a streaming server that was rigged to fail in both of those ways, and it seems resilient.
